// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backspace() {
  return window['go']['main']['App']['Backspace']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function HandleInput(arg1) {
  return window['go']['main']['App']['HandleInput'](arg1);
}

export function ListExercises() {
  return window['go']['main']['App']['ListExercises']();
}

export function StartExercise(arg1) {
  return window['go']['main']['App']['StartExercise'](arg1);
}
