// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backspace() {
  return window['go']['main']['App']['Backspace']();
}

export function GetRender() {
  return window['go']['main']['App']['GetRender']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function KeyPress(arg1) {
  return window['go']['main']['App']['KeyPress'](arg1);
}

export function StartExercise(arg1) {
  return window['go']['main']['App']['StartExercise'](arg1);
}
