// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Backspace():Promise<main.AppState>;

export function GetSession():Promise<main.AppState>;

export function HandleInput(arg1:string):Promise<main.AppState>;

export function ListExercises():Promise<Array<main.Exercise>>;

export function StartExercise(arg1:string):Promise<main.AppState>;
