// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function Backspace():Promise<void>;

export function GetRender():Promise<Array<engine.RenderChar>>;

export function GetStats():Promise<Record<string, number>>;

export function KeyPress(arg1:string):Promise<void>;

export function StartExercise(arg1:string):Promise<void>;
